### ISSUE TITLE
Unable to set environment via middleware settings

### ISSUE THREAD

**Issue by vitush93** [zoltanradics/strapi-middleware-sentry#1]
Explicit middleware settings are getting overridden by:

https://github.com/zoltanradics/strapi-middleware-sentry/blob/b8023d297714a4bc6c92e4d610066bf180387754/lib/index.js#L30

Should be `init({ environment, ...settings })` instead.

**Comment by zoltanradics** [comment]
Sorry for late response, Github did not notify me somehow. In the meantime Strapi came out with official plugin for Sentry so I suggest to use that: https://strapi.io/blog/introducing-sentry-plugin
